services:
  frontend:
    container_name: ibm-frontend
    image: interview-frontend-image
    build: ./frontend
    ports:
      - 4200:80
    expose:
      - 80
    depends_on:
      - backend
  
  backend:
    container_name: ibm-backend
    image: interview-backend-image
    build: ./backend
    ports:
      - 9000:80
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres-db:5432/ibm-interview-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=10ad3079
    depends_on:
      - postgres-db
    
  postgres-db:
    container_name: ibm-database
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=10ad3079
      - POSTGRES_DB=ibm-interview-db

